### ISSUE TITLE
[spam] how to kill thread?

### ISSUE THREAD

**Issue by Devil4ngle** [nomi-san/true-autoit-multi-threading#11]
is there a way to kill thread?

**Comment by Devil4ngle** [comment]
missleading title this is not true multi thread this is just a AdlibUnRegister but worse

**Comment by nomi-san** [comment]
wtf have you said? 🤣🤣

**Comment by Devil4ngle** [comment]
it's not multi thread it is https://www.autoitscript.com/autoit3/docs/functions/AdlibUnRegister.htm but worse

**Comment by nomi-san** [comment]
ik this function, but did you say that "my library is not true multi thread"?
too confusing 🤔

**Comment by Devil4ngle** [comment]
because it is fake multi thread. If you have a lot of pixelsearch in main code for example   and in the side thread  you have a while true consoleWrite("Test")  wend you will see if you remove all the code  from the main thread it will print faster "Test" if you add code to main thread again it will print slower. Making this repository a absolute scam since it's not TRUE multi thread it is fake

**Comment by Devil4ngle** [comment]
you shoud rename it to true-fake-multi-threading

**Comment by nomi-san** [comment]
ahahaha 🤣🤣, you actually dont know what are you saying and how it works.

> remove all the code from the main thread it will print faster "Test"

not related, idk what's in your main thread code, and please remember there's many problems with ConsoleWrite and SciTE output, should use printf and native console (cmd) instead.

**Comment by Devil4ngle** [comment]
> ahahaha 🤣🤣, you actually dont know what are you saying and how it works.
> 
> > remove all the code from the main thread it will print faster "Test"
> 
> not related, idk what's in your main thread code, and please remember there's many problems with ConsoleWrite and SciTE output, should use printf and native console (cmd) instead.

Of course I don't use this multi thread to print console Write  but to send keys to the game where the problem presist. I am tryingto tell you that if there is "heavy" code in main thread in will slow down in side thread making this not a TRUE thread but a fake one since autoit still runs as single process

**Comment by nomi-san** [comment]
there's many ways to proof that side threads are actually running on separate system thread, e.g just call `GetCurrentThreadId()`.

**Comment by Devil4ngle** [comment]
> there's many ways to proof that side threads are actually running on separate system thread, e.g just call `GetCurrentThreadId()`.

I CAN SEE EVIDENCE in front of me if I remove all code from main thread it will run faster in side thread this is a fact

**Comment by nomi-san** [comment]
stop here, you was going out

> still runs as single process

sure you dont know about thread and process.

> remove all code from main thread it will run faster in side thread this is a fact

note thats the autoit's problem, the side threads just start an autoit interpreter in a new system thread.

**Comment by nomi-san** [comment]
in your case, please use multi-process instead
