### ISSUE TITLE
How to Terminate a Thread by ID And ThreadExists?

### ISSUE THREAD

**Issue by Drmon1269** [nomi-san/true-autoit-multi-threading#2]
How about to Kill thread by ID?

**Comment by nomi-san** [comment]
This feature is not implemented to avoid memory leaks (in AutoIt interpreter).
You should use `Exit` statement to (safe) exit immediately in a sub-thread.

```au3
func task($l)
    if not $l.ready then Exit
    ; do something
endfunc
```
